"""empty message

Revision ID: 218ba5e722e6
Revises: 
Create Date: 2019-10-22 17:03:55.853349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '218ba5e722e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('example_model', sa.Column('field1', sa.String(length=50), nullable=True))
    op.add_column('example_model', sa.Column('field2', sa.String(length=50), nullable=True))
    op.add_column('example_model', sa.Column('field3', sa.String(length=50), nullable=True))
    op.add_column('example_model', sa.Column('field4', sa.String(length=50), nullable=True))
    op.add_column('example_model', sa.Column('field5', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'my_model', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'my_model', type_='unique')
    op.drop_column('example_model', 'field5')
    op.drop_column('example_model', 'field4')
    op.drop_column('example_model', 'field3')
    op.drop_column('example_model', 'field2')
    op.drop_column('example_model', 'field1')
    # ### end Alembic commands ###
